### PR TITLE
Add ItyFuzz

### PR DESCRIPTION
**Pull request by shouc**
Adds https://github.com/fuzzland/ityfuzz as a target.

### CODE REVIEW

**Comment by wuestholz** [comment]
Great to see new fuzzers popping up! :) Could you please also add instructions for how to build or pull the docker image in [run-all-fuzzers.sh](https://github.com/ConsenSys/daedaluzz/blob/master/run-all-fuzzers.sh)?

**Comment by wuestholz** [comment]
I tried building the image myself, but ran into an error:

```
Cloning into 'ityfuzz-tmp'...
remote: Enumerating objects: 4021, done.
remote: Counting objects: 100% (344/344), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 4021 (delta 295), reused 296 (delta 276), pack-reused 3677
Receiving objects: 100% (4021/4021), 991.96 KiB | 961.00 KiB/s, done.
Resolving deltas: 100% (2847/2847), done.
Sending build context to Docker daemon  2.178MB
Step 1/34 : FROM rust:buster as environment
 ---> 0a824e32b949
Step 2/34 : RUN apt-get update && apt-get install -y     curl     jq     python3     python3-pip     python3-setuptools     python3-wheel     python3-venv libz3-dev libssl-dev clang pkg-config cmake clang     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> eefe59bb1ab3
Step 3/34 : RUN pip3 install --upgrade pip
 ---> Using cache
 ---> 733645d7dac1
Step 4/34 : RUN mkdir /bins
 ---> Using cache
 ---> 6edbe98dadb6
Step 5/34 : FROM environment as builder
 ---> 6edbe98dadb6
Step 6/34 : WORKDIR /builder
 ---> Using cache
 ---> fc291d6b6d07
Step 7/34 : COPY Cargo.toml .
 ---> Using cache
 ---> a8ffb71d2948
Step 8/34 : COPY rust-toolchain.toml .
 ---> Using cache
 ---> 5934c4581240
Step 9/34 : COPY src ./src
 ---> Using cache
 ---> 9c835c780f9a
Step 10/34 : COPY cli ./cli
 ---> Using cache
 ---> 8bbd9a2ec90d
Step 11/34 : COPY benches ./benches
 ---> Using cache
 ---> c0a95e0c80fe
Step 12/34 : COPY externals ./externals
 ---> Using cache
 ---> 90552b6916d1
Step 13/34 : WORKDIR /builder/cli
 ---> Using cache
 ---> 97adf8a60b9c
Step 14/34 : RUN cargo build --release
 ---> Running in 1d1b76d70b96
info: syncing channel updates for 'nightly-2023-04-09-x86_64-unknown-linux-gnu'
info: latest update on 2023-04-09, rust version 1.70.0-nightly (af06dce64 2023-04-08)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
    Updating crates.io index
error: failed to get `heimdall` as a dependency of package `ityfuzz v0.1.0 (/builder)`
    ... which satisfies path dependency `ityfuzz` of package `cli v0.1.0 (/builder/cli)`

Caused by:
  failed to load source for dependency `heimdall`

Caused by:
  Unable to update /builder/externals/heimdall-rs/heimdall

Caused by:
  failed to read `/builder/externals/heimdall-rs/heimdall/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
```

I used the following steps:

```
rm -rf ityfuzz-tmp
git clone https://github.com/fuzzland/ityfuzz.git ityfuzz-tmp
cd ityfuzz-tmp
docker build --rm -t "fuzzland/ityfuzz:v0.0.1" -f Dockerfile .
```

**Comment by stanfordreject** [comment]
Thanks! I have added the pulling commands to `run-all-fuzzers.sh`. For building the image locally, you need to run `git submodule update --init` first before running `docker build`.

**Comment by wuestholz** [comment]
@stanfordreject Great! Thanks a lot!

**Pull request merged**
